version: '3'
services:
  prod:
    build:
      context: ../app
      dockerfile: Dockerfile
    image: java-app-image
    container_name: prod
    ports:
      - "3002:8080"
    restart: unless-stopped
